[package]
name = "hf_transfer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "hf_transfer"
crate-type = ["cdylib"]

[dependencies]
futures = "0.3.25"
pyo3 = { version = "0.17.3", features = ["extension-module"] }
reqwest = { version = "0.11.13", features = ["rustls-tls"] }
tokio = { version = "1.23.0", features = ["rt", "rt-multi-thread", "fs"] }
